Repository googleapis/python-recommendations-ai, pull requests merged in 2021-04, with the labels that each got.

#26 chore: tweak docstrings
  google/cloud/recommendationengine/py.typed
  google/cloud/recommendationengine_v1beta1/py.typed
  google/cloud/recommendationengine_v1beta1/services/catalog_service/async_client.py
  google/cloud/recommendationengine_v1beta1/services/catalog_service/client.py
  google/cloud/recommendationengine_v1beta1/services/prediction_api_key_registry/async_client.py
  google/cloud/recommendationengine_v1beta1/services/prediction_api_key_registry/client.py
  google/cloud/recommendationengine_v1beta1/services/prediction_service/async_client.py
  google/cloud/recommendationengine_v1beta1/services/prediction_service/client.py
  google/cloud/recommendationengine_v1beta1/services/user_event_service/async_client.py
  google/cloud/recommendationengine_v1beta1/services/user_event_service/client.py
  google/cloud/recommendationengine_v1beta1/types/catalog_service.py
  google/cloud/recommendationengine_v1beta1/types/import_.py
  google/cloud/recommendationengine_v1beta1/types/prediction_apikey_registry_service.py
  google/cloud/recommendationengine_v1beta1/types/prediction_service.py
  google/cloud/recommendationengine_v1beta1/types/user_event_service.py
  synth.metadata
Labels: api: recommendationengine, automerge, cla: yes, context: partial

#30 chore: start tracking obsolete files
  synth.metadata
Labels: api: recommendationengine, cla: yes, context: full

#32 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  google/cloud/recommendationengine_v1beta1/__init__.py
  synth.metadata
Labels: api: recommendationengine, cla: yes, context: partial

#36 chore: prevent normalization of semver versioning
  setup.py
Labels: api: recommendationengine, cla: yes

#38 chore(revert): revert preventing normalization
  setup.py
Labels: api: recommendationengine, automerge, cla: yes
